import type { InvoiceProfileConfig } from "../types";

export const hrFields: InvoiceProfileConfig = {
  id: "hr",
  label: "Hrvaška",
  description: "HR Fiskalizacija 2.0 / HR-CIUS z OIB, operaterjem in KPD.",
  requiredFields: [
    "hrData.issueTime",
    "hrData.businessProcessType",
    "hrData.operatorOib",
    "hrData.operatorCode",
    "line.kpdCode",
    "line.hrVatCategoryCode",
  ],
  optionalFields: ["hrData.previousInvoiceNumber", "hrData.selfBilling"],
  sections: ["base", "buyer", "lines", "payment", "hr"],
  profileFields: [
    {
      name: "businessProcessType",
      label: "Business process type",
      type: "select",
      required: true,
      helper: "P1-P12 ali P99 za kupcevo posebno oznako procesa.",
      options: [
        "P1",
        "P2",
        "P3",
        "P4",
        "P5",
        "P6",
        "P7",
        "P8",
        "P9",
        "P10",
        "P11",
        "P12",
        "P99",
      ].map((value) => ({ label: value, value })),
    },
    {
      name: "p99BuyerProcessId",
      label: "Kupceva oznaka procesa",
      type: "text",
      helper: "Obvezno samo, kadar je business process P99.",
      placeholder: "npr. oznaka kupca",
    },
    {
      name: "issueTime",
      label: "Cas izdaje",
      type: "time",
      required: true,
      helper: "Format HH:MM:SS; HR-BT-2.",
    },
    {
      name: "operatorOib",
      label: "OIB operaterja",
      type: "text",
      required: true,
      helper: "11 stevk; HR-BT-5.",
    },
    {
      name: "operatorCode",
      label: "Oznaka operaterja",
      type: "text",
      required: true,
      helper: "HR-BT-4.",
    },
    {
      name: "previousInvoiceNumber",
      label: "Predhodni racun",
      type: "text",
      helper: "Izpolni pri sklicu na predhodni racun.",
    },
    {
      name: "previousInvoiceDate",
      label: "Datum predhodnega racuna",
      type: "date",
    },
    {
      name: "isCopy",
      label: "Kopija racuna",
      type: "checkbox",
    },
    {
      name: "selfBilling",
      label: "Samoizdaja",
      type: "checkbox",
      helper: "Uporabi skupaj s P12, kadar je racun samoizdan.",
    },
    {
      name: "hrVatCategoryCode",
      label: "HR DDV oznaka",
      type: "text",
      scope: "line",
      required: true,
      helper: "HR oznaka DDV kategorije za postavko.",
    },
    {
      name: "kpdCode",
      label: "KPD koda",
      type: "text",
      scope: "line",
      required: true,
      helper: "BT-158 klasifikacija artikla, npr. 62.01.11.",
    },
  ],
};
